---
version: 2

project_name: e2c

before:
  hooks:
    - go mod tidy

builds:
  - id: e2c
    binary: e2c
    dir: cmd/e2c
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'

# Changelog configuration (will be in the github release).
changelog:
  use: github-native
  sort: asc
  # groups:
  #   - title: "âœ¨ Features"
  #     regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
  #     order: 0
  #   - title: "ðŸ› Bug fixes"
  #     regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
  #     order: 1
  #   - title: "ðŸ“š Documentation"
  #     regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
  #     order: 2
  #   - title: "ðŸŒ± Others"
  #     order: 999
  filters:
    exclude:
      - "^test:"
      - '^ci:'

release:
  draft: true
  replace_existing_draft: true

# A footer to add to all releases.
# release:
#   footer: >-

#     ---

#     Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

# Enables source archives.
# source:
#   enabled: true

# Creates archives for each target.
archives:
  # - formats: [ 'tar.gz' ]
  #   # this name template makes the OS and Arch compatible with the results of `uname`.
  #   name_template: >-
  #     {{ .ProjectName }}_
  #     {{- title .Os }}_
  #     {{- if eq .Arch "amd64" }}x86_64
  #     {{- else if eq .Arch "386" }}i386
  #     {{- else }}{{ .Arch }}{{ end }}
  #   # use zip for windows archives
  #   format_overrides:
  #     - goos: windows
  #       formats: [ 'zip' ]
  - formats: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}_v{{- .Version }}"
    ids:
      - e2c

# Creates Linux packages.
# nfpms:
#   - file_name_template: "{{ .ConventionalFileName }}"
#     maintainer: Nicolas Lamirault <nicolas.lamirault@gmail.com>
#     formats:
#       - deb
#       - apk
#       - rpm

# SBOMs for the archives.
sboms:
  - id: spdx
    artifacts: binary

# # Sign binaries with cosign.
# signs:
#   - cmd: cosign
#     certificate: "${artifact}.pem"
#     args:
#       - sign-blob
#       - "--output-certificate=${certificate}"
#       - "--output-signature=${signature}"
#       - "${artifact}"
#       - "--yes"
#     artifacts: checksum

brews:
  - repository:
      owner: nlamirault
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    directory: Formula
    homepage: https://github.com/nlamirault/e2c
    description: e2c is AWS EC2 Terminal UI Manager. Inspired by k9s and e1s.
    license: Apache v2
