---
version: 2

project_name: e2c

before:
  hooks:
    - go mod download

builds:
  - binary: e2c
    dir: cmd/e2c
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

# Changelog configuration (will be in the github release).
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - '^ci:'

universal_binaries:
  - replace: true

# Enables source archives.
source:
  enabled: true

# Creates archives for each target.
archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

# Creates Linux packages.
nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    maintainer: Nicolas Lamirault <nicolas.lamirault@gmail.com>
    formats:
      - deb
      - apk
      - rpm

# # SBOMs for the archives.
# sboms:
#   - artifacts: archive

# # Sign binaries with cosign.
# signs:
#   - cmd: cosign
#     certificate: "${artifact}.pem"
#     args:
#       - sign-blob
#       - "--output-certificate=${certificate}"
#       - "--output-signature=${signature}"
#       - "${artifact}"
#       - "--yes"
#     artifacts: checksum

brews:
  - repository:
      owner: e2c
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    directory: Formula
    homepage: https://github.com/nlamirault/e2c
    description: e2c is AWS EC2 Terminal UI Manager. Inspired by k9s and e1s.
    license: Apache v2

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

# A footer to add to all releases.
# release:
#   footer: >-

#     ---

#     Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - name: e2c
    homepage: https://github.com/nlamirault/e2c
    description: e2c is AWS EC2 Terminal UI Manager. Inspired by k9s and e1s.
    tap:
      owner: nlamirault
      name: homebrew-tap

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
