---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: e2c

before:
  hooks:
    - go mod tidy

# https://goreleaser.com/customization/build
builds:
  - id: e2c
    binary: e2c
    dir: cmd/e2c
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

checksum: # https://goreleaser.com/customization/checksum/
  name_template: "checksums.txt"
  algorithm: sha256

# Changelog configuration (will be in the github release).
# https://goreleaser.com/customization/changelog/
changelog:
  use: github-native
  sort: asc
  # groups:
  #   - title: "✨ Features"
  #     regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
  #     order: 0
  #   - title: "🐛 Bug fixes"
  #     regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
  #     order: 1
  #   - title: "📚 Documentation"
  #     regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
  #     order: 2
  #   - title: "🌱 Others"
  #     order: 999
  filters:
    exclude:
      - "^test:"
      - '^ci:'

# https://goreleaser.com/customization/release/
release:
  # draft: true
  replace_existing_draft: true
  # name_template: "{{ .ProjectName }} {{ .Tag }}"
  header: |
    Released on {{ .Date }}

# Enables source archives.
# source:
#   enabled: true

# Creates archives for each target.
# https://goreleaser.com/customization/archive/
archives:
  # - formats: [ 'tar.gz' ]
  #   # this name template makes the OS and Arch compatible with the results of `uname`.
  #   name_template: >-
  #     {{ .ProjectName }}_
  #     {{- title .Os }}_
  #     {{- if eq .Arch "amd64" }}x86_64
  #     {{- else if eq .Arch "386" }}i386
  #     {{- else }}{{ .Arch }}{{ end }}
  #   # use zip for windows archives
  #   format_overrides:
  #     - goos: windows
  #       formats: [ 'zip' ]
  - formats: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}_v{{- .Version }}"
    ids:
      - e2c

# Creates Linux packages.
# nfpms:
#   - file_name_template: "{{ .ConventionalFileName }}"
#     maintainer: Nicolas Lamirault <nicolas.lamirault@gmail.com>
#     formats:
#       - deb
#       - apk
#       - rpm

# # creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
sboms:
  - id: spdx
    artifacts: binary
  # - id: spdx
  #   artifacts: archive

# signs the checksum file
# all files (including the sboms) are included in the checksum, so we don't need to sign each one if we don't want to
# https://goreleaser.com/customization/sign
# signs:
#   - cmd: cosign
#     certificate: "${artifact}.pem"
#     args:
#       - sign-blob
#       - "--output-certificate=${certificate}"
#       - "--output-signature=${signature}"
#       - "${artifact}"
#       - "--yes" # needed on cosign 2.0.0+
#     artifacts: checksum
#     output: true

brews:
  - repository:
      owner: nlamirault
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    directory: Formula
    homepage: https://github.com/nlamirault/e2c
    description: e2c is AWS EC2 Terminal UI Manager. Inspired by k9s and e1s.
    license: Apache v2
